# 10 · Pipelines y contrato de entrenamiento

Fase F, paso 31. Consulte [LEEME_FASE_F.md](LEEME_FASE_F.md). Se verifica la ejecución E y se congelan configuración, familias, candidatos, predictores y evaluación. **Modo diagnóstico:** los ajustes ensayan el código con candidatos; no autorizan producción ni validan las etiquetas.

In [ ]:
from pathlib import Path
import sys, importlib
import pandas as pd
from IPython.display import display
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p/'src/geoau/training.py').is_file())
if str(ROOT/'src') not in sys.path: sys.path.insert(0, str(ROOT/'src'))
from geoau import training as tr
from geoau import evaluation as ev
importlib.reload(tr)

RUN = tr.ensure_run(ROOT)
display(ev.read_json(RUN/"control_cierre.json"))
display(ev.read_json(RUN/"config_snapshot.json"))

Fase F: C:\Users\Lenovo\Desktop\PROYECTO IA\Proyecto Con Luis\reports\fase_f\20260909T184735_016759Z

{'estado_ejecucion': 'en_curso',
 'mode': 'diagnostic',
 'scientific_training_allowed': False,
 'prediction_allowed': False}

{'schema_version': 1,
 'phase_e_run': 'reports/fase_e/20260909T124128_606717Z',
 'output_directory': 'reports/fase_f',
 'mode': 'diagnostic',
 'allow_diagnostic_fit': True,
 'seed': 42,
 'search_trials': 3,
 'forest_trees': 500,
 'ablation_trees': 150,
 'n_jobs': 2,
 'prediction_batch_size': 20000,
 'evaluation_background_size': 10000,
 'ratios_u_to_p': [3, 1, 10],
 'pu_realizations': [0, 1, 2],
 'fit_weighting': 'none',
 'primary_metric': 'recovery_at_05',
 'feature_set': 'geology_terrain_geo4_hydro',
 'families': ['logistic', 'random_forest', 'extra_trees', 'hist_boosting']}

## Columnas y transformaciones
Solo entran predictores de la lista D. Se excluyen coordenadas, IDs, etiquetas, grupos y pesos. Las categorías y clases geoquímicas se codifican como categorías, con estados explícitos para ausente/desconocido. La mediana, categorías y escalado de regresión logística se aprenden en cada entrenamiento interno. El boosting desactiva la validación aleatoria implícita de early stopping.

In [ ]:
schema = ev.read_json(RUN/'feature_schema.json')
display(pd.DataFrame([{'set': name, 'predictors': len(v['columns']), 'categorical': len(v['categorical'])}
                      for name, v in schema.items()]))
display(ev.read_json(RUN/'candidates.json'))

                           set  predictors  categorical
0                      geology          79            2
1              geology_terrain          85            2
2  geology_terrain_pathfinders          88            5
3         geology_terrain_geo4          89            6
4   geology_terrain_geo4_hydro          93            6
5             geo4_proportions         120            2

{'logistic': [{'candidate_id': 'logistic_00',
   'family': 'logistic',
   'ratio': 3,
   'params': {'C': 1.0}},
  {'candidate_id': 'logistic_01',
   'family': 'logistic',
   'ratio': 1,
   'params': {'C': 0.1}},
  {'candidate_id': 'logistic_02',
   'family': 'logistic',
   'ratio': 10,
   'params': {'C': 10.0}}],
 'random_forest': [{'candidate_id': 'random_forest_00',
   'family': 'random_forest',
   'ratio': 3,
   'params': {'n_estimators': 500,
    'min_samples_leaf': 5,
    'max_features': 'sqrt',
    'max_depth': None}},
  {'candidate_id': 'random_forest_01',
   'family': 'random_forest',
   'ratio': 1,
   'params': {'n_estimators': 500,
    'min_samples_leaf': 20,
    'max_features': 0.5,
    'max_depth': None}},
  {'candidate_id': 'random_forest_02',
   'family': 'random_forest',
   'ratio': 10,
   'params': {'n_estimators': 500,
    'min_samples_leaf': 2,
    'max_features': 'sqrt',
    'max_depth': 16}}],
 'extra_trees': [{'candidate_id': 'extra_trees_00',
   'family': 'extra_trees',
   'ratio': 3,
   'params': {'n_estimators': 500,
    'min_samples_leaf': 5,
    'max_features': 'sqrt',
    'max_depth': None}},
  {'candidate_id': 'extra_trees_01',
   'family': 'extra_trees',
   'ratio': 1,
   'params': {'n_estimators': 500,
    'min_samples_leaf': 2,
    'max_features': 0.5,
    'max_depth': 8}},
  {'candidate_id': 'extra_trees_02',
   'family': 'extra_trees',
   'ratio': 10,
   'params': {'n_estimators': 500,
    'min_samples_leaf': 10,
    'max_features': 0.5,
    'max_depth': 16}}],
 'hist_boosting': [{'candidate_id': 'hist_boosting_00',
   'family': 'hist_boosting',
   'ratio': 3,
   'params': {'max_iter': 100,
    'learning_rate': 0.1,
    'max_leaf_nodes': 15,
    'min_samples_leaf': 10}},
  {'candidate_id': 'hist_boosting_01',
   'family': 'hist_boosting',
   'ratio': 1,
   'params': {'max_iter': 100,
    'learning_rate': 0.05,
    'max_leaf_nodes': 31,
    'min_samples_leaf': 10}},
  {'candidate_id': 'hist_boosting_02',
   'family': 'hist_boosting',
   'ratio': 10,
   'params': {'max_iter': 100,
    'learning_rate': 0.15,
    'max_leaf_nodes': 7,
    'min_samples_leaf': 10}}]}

## Protocolo predefinido
Selección por recuperación de candidatos al priorizar el 5 % del área en validación interna. En modo validado se cuenta una vez cada depósito. Empates por hash de celda independiente de las etiquetas. AP y ROC-AUC P/U se calculan en una muestra fija de evaluación y no miden descubrimiento real. No se generan predicciones de la reserva.

El piloto usa tres candidatos por familia y ratios 3/1/10. La referencia de Random Forest tiene 500 árboles, hoja mínima 5 y `max_features="sqrt"`. La configuración permite ampliar la búsqueda en una nueva ejecución.

---

# Extensión Geoquímica (64 Predictores · Atlas IGME): 10 · Pipelines y contrato de entrenamiento

GeoAI integra **64 predictores**, incluidas ocho variables geoquímicas, sobre una malla de un kilómetro. Este cuaderno desarrolla su etapa utilizando la configuración común. El notebook 18 reúne el sistema completo. Las celdas de consulta leen resultados entrenados; el indicador de reentrenamiento permite regenerarlos.

In [1]:
from pathlib import Path
import sys, json
import pandas as pd
from IPython.display import display, Image
ROOT_GEO = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / 'src/geoau/geochemical_experiment.py').is_file())
if str(ROOT_GEO / 'src') not in sys.path:
    sys.path.insert(0, str(ROOT_GEO / 'src'))
RESULTS_GEO = ROOT_GEO / 'reports/geoquimica_20261017'
REPORT_GEO = ROOT_GEO / 'informes/geoquimica_20261017'
REENTRENAR_GEOQUIMICA = False  # True vuelve a ejecutar datos, CV, rotaciones, mapas e informe.
if REENTRENAR_GEOQUIMICA:
    from geoau.geochemical_experiment import run_experiment
    run_experiment(ROOT_GEO)
if not (RESULTS_GEO / 'control_ejecucion.json').is_file():
    raise FileNotFoundError('Ejecutar primero scripts/ejecutar_geoquimica.py con el entorno .venv-fase-a.')
control_geo = json.loads((RESULTS_GEO / 'control_ejecucion.json').read_text(encoding='utf-8'))
assert control_geo['status'] == 'complete' and control_geo['n_input_features'] == 64
print('Ejecución:', RESULTS_GEO)
print('GeoAI · 64 predictores · ocho variables geoquímicas · score relativo P/U')

Ejecución: C:\Users\Lenovo\Desktop\PROYECTO IA\GeoAI\GeoAI\reports\geoquimica_20261017
GeoAI · 64 predictores · ocho variables geoquímicas · score relativo P/U

## 1. Contrato de los 64 predictores

Una fila representa una celda de un kilómetro EPSG:25830. Se integran 19 fracciones litológicas, 27 fracciones de edades, tres distancias estructurales, seis variables del relieve, una hidrológica y ocho geoquímicas. Identificadores, coordenadas, pesos y bloques no son covariables. El dominio se define por el soporte geológico y de relieve, conservando las ausencias geoquímicas.

In [2]:
variables = pd.read_csv(RESULTS_GEO / 'variables_incluidas.csv')
assert len(variables) == 64 and variables.variable.is_unique
display(variables.groupby(['family','representation']).size().rename('variables').reset_index())
display(variables)

        family           representation  variables
0       Edades                  numeric         27
1  Estructuras                  numeric          3
2   Geoquímica  categorical_atlas_class          8
3  Hidrografía                  numeric          1
4    Litología                  numeric         19
5      Relieve                  numeric          6

,variable,family,representation,included_in_model,is_analytical_concentration,significado_geologico,fuente,metodo_calculo,unidades,tratamiento_nodata,riesgo_leakage_circularidad
0,litologia_u000_fraccion,Litología,numeric,True,False,Fracción superficial ocupada por la unidad: Ar...,IGME (GEODE Mapa Geológico Continuo 1:50.000 /...,"intersección exacta; fracción de unidad mixta,...","fracción (m2/m2 terrestre, [0, 1])",Asignación de 0.0 cuando la unidad no está pre...,Nulo. Cartografía geológica básica levantada d...
1,litologia_u001_fraccion,Litología,numeric,True,False,Fracción superficial ocupada por la unidad: Ar...,IGME (GEODE Mapa Geológico Continuo 1:50.000 /...,"intersección exacta; fracción de unidad mixta,...","fracción (m2/m2 terrestre, [0, 1])",Asignación de 0.0 cuando la unidad no está pre...,Nulo. Cartografía geológica básica levantada d...
2,litologia_u002_fraccion,Litología,numeric,True,False,Fracción superficial ocupada por la unidad: Ca...,IGME (GEODE Mapa Geológico Continuo 1:50.000 /...,"intersección exacta; fracción de unidad mixta,...","fracción (m2/m2 terrestre, [0, 1])",Asignación de 0.0 cuando la unidad no está pre...,Nulo. Cartografía geológica básica levantada d...
3,litologia_u003_fraccion,Litología,numeric,True,False,Fracción superficial ocupada por la unidad: Ca...,IGME (GEODE Mapa Geológico Continuo 1:50.000 /...,"intersección exacta; fracción de unidad mixta,...","fracción (m2/m2 terrestre, [0, 1])",Asignación de 0.0 cuando la unidad no está pre...,Nulo. Cartografía geológica básica levantada d...
4,litologia_u004_fraccion,Litología,numeric,True,False,Fracción superficial ocupada por la unidad: Co...,IGME (GEODE Mapa Geológico Continuo 1:50.000 /...,"intersección exacta; fracción de unidad mixta,...","fracción (m2/m2 terrestre, [0, 1])",Asignación de 0.0 cuando la unidad no está pre...,Nulo. Cartografía geológica básica levantada d...
...,...,...,...,...,...,...,...,...,...,...,...
59,hg_clase_modal,Geoquímica,categorical_atlas_class,True,False,Clase cartográfica modal de HG por celda; cont...,"IGME (Atlas Geoquímico de España, digitalizaci...",Clasificación de paleta RGB con control de dis...,Categoría cartográfica; los intervalos locales...,NaN -> categoría -1; clase cero válida; one-ho...,Revisar procedencia y esfuerzo de muestreo; no...
60,cu_clase_modal,Geoquímica,categorical_atlas_class,True,False,Clase cartográfica modal de CU por celda; cont...,"IGME (Atlas Geoquímico de España, digitalizaci...",Clasificación de paleta RGB con control de dis...,Categoría cartográfica; los intervalos locales...,NaN -> categoría -1; clase cero válida; one-ho...,Revisar procedencia y esfuerzo de muestreo; no...
61,pb_clase_modal,Geoquímica,categorical_atlas_class,True,False,Clase cartográfica modal de PB por celda; cont...,"IGME (Atlas Geoquímico de España, digitalizaci...",Clasificación de paleta RGB con control de dis...,Categoría cartográfica; los intervalos locales...,NaN -> categoría -1; clase cero válida; one-ho...,Revisar procedencia y esfuerzo de muestreo; no...
62,zn_clase_modal,Geoquímica,categorical_atlas_class,True,False,Clase cartográfica modal de ZN por celda; cont...,"IGME (Atlas Geoquímico de España, digitalizaci...",Clasificación de paleta RGB con control de dis...,Categoría cartográfica; los intervalos locales...,NaN -> categoría -1; clase cero válida; one-ho...,Revisar procedencia y esfuerzo de muestreo; no...
63,w_clase_modal,Geoquímica,categorical_atlas_class,True,False,Clase cartográfica modal de W por celda; conte...,"IGME (Atlas Geoquímico de España, digitalizaci...",Clasificación de paleta RGB con control de dis...,Categoría cartográfica; los intervalos locales...,NaN -> categoría -1; clase cero válida; one-ho...,Revisar procedencia y esfuerzo de muestreo; no...

## 2. Preprocesamiento dentro del entrenamiento

Las variables numéricas se imputan con la mediana, añaden indicadores de ausencia cuando procede y se estandarizan. Las clases geoquímicas se imputan como categoría -1 y se codifican con one-hot. Cada algoritmo contiene estas transformaciones en un Pipeline ajustado exclusivamente con el entrenamiento de su partición. La aplicación territorial usa el pipeline ya aprendido.

In [3]:
from geoau.geochemical_experiment import load_data, make_preprocessor
data = load_data(ROOT_GEO)
display(make_preprocessor(data.feature_columns, data.config['geochemical_columns']))
print('Entradas:', len(data.feature_columns))
print('Geoquímicas:', data.config['geochemical_columns'])

ColumnTransformer(sparse_threshold=0.0,
                  transformers=[('numeric',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(add_indicator=True,
                                                                keep_empty_features=True,
                                                                strategy='median')),
                                                 ('scale', StandardScaler())]),
                                 ['litologia_u000_fraccion',
                                  'litologia_u001_fraccion',
                                  'litologia_u002_fraccion',
                                  'litologia_u003_fraccion',
                                  'litologia_u004_fraccion',
                                  'litologia_u005_fracci...
                                ('geochemical',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(fill_value=-1,
                                                                keep_empty_features=True,
                                                                strategy='constant')),
                                                 ('encode',
                                                  OneHotEncoder(dtype=<class 'numpy.float32'>,
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['as_clase_modal', 'sb_clase_modal',
                                  'bi_clase_modal', 'hg_clase_modal',
                                  'cu_clase_modal', 'pb_clase_modal',
                                  'zn_clase_modal', 'w_clase_modal'])])

Entradas: 64
Geoquímicas: ['as_clase_modal', 'sb_clase_modal', 'bi_clase_modal', 'hg_clase_modal', 'cu_clase_modal', 'pb_clase_modal', 'zn_clase_modal', 'w_clase_modal']

## 3. Aprendizaje P/U y confianza del inventario

Las celdas con indicios forman P y el territorio no inventariado es U, cuyo estado de mineralización se desconoce. Se muestrean hasta tres U por P con semillas fijadas. Las confirmadas reciben peso 1, las pendientes 0,5 y U peso 1. Las métricas se calculan sin ponderación. Bagging PU conserva P y remuestrea U dentro de cada ajuste; la ausencia de registros no se transforma en una ausencia geológica demostrada.

In [4]:
sample = pd.read_parquet(RESULTS_GEO / 'partitions/benchmark_sample.parquet')
assert sample.cell_id.is_unique
display(sample.groupby(['label','peso_confianza']).size().rename('celdas').reset_index())
display(pd.DataFrame([json.loads((RESULTS_GEO / 'partitions/benchmark_design.json').read_text(encoding='utf-8'))]))

   label  peso_confianza  celdas
0      0             1.0    1887
1      1             0.5     517
2      1             1.0     112

,reserved_blocks_excluded,sample_hash,n_P,n_U,cv_buffer_m,block_size_m
0,"[0_95, 0_96, 11_81, 5_83, 6_87, 9_82]",00ce7bef1a7ff2cc5670024db9f901acf7d1725f9339b4...,629,1887,15000,50000

## 4. Validación espacial por bloques y buffer

Se utilizan cinco pliegues por bloques de 50 km. Los bloques de los distritos de reserva quedan fuera del pool de evaluación de algoritmos. En cada pliegue se excluyen del entrenamiento las muestras situadas a menos de 15 km de las muestras de validación. Cada muestra se predice fuera de pliegue una vez. Se exportan pertenencias y hashes para comprobar la separación. Todos los algoritmos utilizan las mismas 64 variables y particiones.

In [5]:
folds = pd.read_csv(RESULTS_GEO / 'benchmark_folds.csv')
assert folds.groupby('fold').training_ids_sha256.nunique().eq(1).all()
assert folds.groupby('fold').validation_ids_sha256.nunique().eq(1).all()
display(folds.loc[folds.model.eq('bagging_pu'),['fold','train_cells','validation_cells','buffer_excluded','roc_auc']].round(4))
display(pd.read_parquet(RESULTS_GEO / 'partitions/benchmark_memberships.parquet').groupby(['fold','role']).size().to_frame('celdas'))

    fold  train_cells  validation_cells  buffer_excluded  roc_auc
15     0         1785               503              228   0.9111
16     1         1841               500              175   0.9350
17     2         1610               646              260   0.8678
18     3         1860               412              244   0.8823
19     4         1841               455              220   0.8754

                      celdas
fold role
0    buffer_excluded     228
     train              1785
     validation          503
1    buffer_excluded     175
     train              1841
     validation          500
2    buffer_excluded     260
     train              1610
     validation          646
3    buffer_excluded     244
     train              1860
     validation          412
4    buffer_excluded     220
     train              1841
     validation          455

## 5. Reproducción y uso

Configuración: config/geoquimica_20261017.yaml. Lógica: src/geoau/geochemical_experiment.py. Ejecución: .venv-fase-a/Scripts/python.exe scripts/ejecutar_geoquimica.py. Se admiten etapas audit, benchmark, rotations, maps y report. Para ejecutar todos los cuadernos: scripts/actualizar_notebooks_geoquimica.py --execute. REENTRENAR_GEOQUIMICA=True en la primera celda ejecuta la cadena completa antes de consultar resultados.

Los manifiestos SHA-256 conservan entradas, código y salidas. Se exportan entorno, variables, cobertura, leyendas, muestras, particiones, pesos y modelos. El notebook 18 reúne el sistema y el informe desarrolla sus datos y resultados. Uso: priorización regional con revisión geológica. El contraste de las leyendas y una campaña externa completan su evaluación.

In [6]:
display(pd.DataFrame([control_geo]))
print('Informe:',REPORT_GEO / 'INFORME_RESULTADOS_GEOQUIMICA.md')
print('Configuración:',ROOT_GEO / 'config/geoquimica_20261017.yaml')

,status,models_retrained,n_cv_results,n_rotation_results,n_cells,n_input_features,geoquimica_incluida,absolute_probability
0,complete,True,4,3,478443,64,True,False

Informe: C:\Users\Lenovo\Desktop\PROYECTO IA\GeoAI\GeoAI\informes\geoquimica_20261017\INFORME_RESULTADOS_GEOQUIMICA.md
Configuración: C:\Users\Lenovo\Desktop\PROYECTO IA\GeoAI\GeoAI\config\geoquimica_20261017.yaml